### ISSUE TITLE
Hard-coded fiducial volume cut in PFO Characterisation MVA training

### ISSUE THREAD

**Issue by etyley** [PandoraPFA/LArContent#148]
Recent changes to the `MvaPfoCharacterisationAlgorithm` have introduced a fiducial volume cut that is experiment specific, presumably for DUNE FD, which cuts out almost half of SBND. 
https://github.com/PandoraPFA/LArContent/blob/7a4a75eb28607d1df6381051dbb1d65f50aa9257/larpandoracontent/LArTrackShowerId/MvaPfoCharacterisationAlgorithm.cc#L235 
Ideally this would be made generic for any experiment using the distances from the detector faces rather than hard-coded positions.

**Comment by AndyChappell** [comment]
This issue was fixed in [LArContent v03_22_01](https://github.com/PandoraPFA/LArContent/commit/bd1bd5a5f5bd8e123376e047c2ecd74b6ce70969#diff-056fa08c1a4b1cd08e3987f2494e61e82fca804ae53be0dd8ab377e92644ae8a)
