### ISSUE TITLE
Saving Nu ID features in output

### ISSUE THREAD

**Issue by brucehoward-physics** [PandoraPFA/LArContent#188]
It would be useful to have the features calculated as inputs to the Nu ID saved in the art files to facilitate a better understanding of the output score and, say, data/MC comparisons.

An ICARUS graduate student - Jack Smedley - had a conversation with Ed Tyley about getting these into our outputs and Ed suggested using the metadata (which is used for the score itself) could be a good path forward. I put together this feature branch that works in that direction: https://github.com/brucehoward-physics/LArContent/tree/feature/howard_writeNuIdFeatures

It still needs to be tested so it's not quite ready for a PR yet, but I wanted to get this into the minds of folks to have a look/discussion/etc., as appropriate, sooner than later.

**Comment by brucehoward-physics** [comment]
Ah! Sure, would be happy to coordinate with Henry -- I'll send him a message in private. Cheers!

**Comment by henrylay97** [comment]
Hi all, Bruce and I have discussed offline. I have a similar [branch](https://github.com/henrylay97/LArContent/tree/feature/hlay_persist_slice_bdt_inputs) that I have been using, and discussed with @AndyChappell last week (including the use of a map between the names and values). I have shamelessly stolen Bruce's use of an xml parameter to control this and added it to my branch. I'm of the opinion that this branch is ready for a PR, there are at least two current use cases and its totally backwards compatible. What do people think?

**Comment by brucehoward-physics** [comment]
Thanks for commenting here about our conversation @henrylay97 😄

I've done a quick though not rigorous test (for completeness: with the branch as of last night, so not with the XML param) and it seemed quite straightforward to adapt what I had done on the SBN/ICARUS side with this idea to work with your LArContent branch. That is, to get the products into the analysis files we were interested in.

From my side, then, happy to go with using the branch that you've already worked on and discussed with Andy!

**Comment by henrylay97** [comment]
Fab thanks Bruce! Just to clarify, is it the naming in the strings that requires changes on your side? If so, happy to change them to match yours?

**Comment by brucehoward-physics** [comment]
Yeah I believe some capitalization that was all I had to change, well that and I'll add the new XML parameter name - but I think I prefer your naming scheme better on both accounts.

**Comment by PetrilloAtWork** [comment]
Related: pull request #189.

**Comment by AndyChappell** [comment]
Resolved in larpandoracontent PR [45](https://github.com/LArSoft/larpandoracontent/pull/45).
