### ISSUE TITLE
Repeated checks

### ISSUE THREAD

**Issue by a-d-smith** [PandoraPFA/LArContent#25]
https://github.com/PandoraPFA/LArContent/blob/86c00ba9f438f225a0d14c0708a7f91587449709/larpandoracontent/LArHelpers/LArInteractionTypeHelper.cc#L35-L53

I think the checks on these lines have already been done in `SelectReconstructableMCParticles`, which calls `SelectParticlesByHitCount`

**Comment by PandoraPFA** [comment]
Resolved.
