### ISSUE TITLE
Neutrino ID Tool Purity and Completeness 

### ISSUE THREAD

**Issue by StevenGreen1** [PandoraPFA/LArContent#41]
When working out purities and completenesses used for determining whether a slice is the best slice to use for training the neutrino ID, the nMCHits only includes hits if they're in a slice.  Therefore, any hits that are accidentally added to a clear through going cosmic ray will not be counted properly.

I don't think this is a particularly large issue especially given the metrics all look ok, but it might be worth calculating nMCHits from the current calo hit list so that purity and completeness are the same as used in the event validation algorithm.

Code: https://github.com/PandoraPFA/LArContent/blob/172e2a29683d1538989d075a1c78c9180b1d82f4/larpandoracontent/LArControlFlow/NeutrinoIdTool.cc#L89

**Comment by PandoraPFA** [comment]
As discussed, this sounds very sensible (means the purity and completeness variables will be much better defined). Please do submit a PR, with @a-d-smith to ensure that the uboone treatment is the same.
