### ISSUE TITLE
Identical Return Functions

### ISSUE THREAD

**Issue by StevenGreen1** [PandoraPFA/LArContent#43]
The two return functions in a function in the LArSupportVectorMachine header file are identical.  There is a check on the sign of a variable (scaledScore) before returning a function, but in both cases the returned function is identical.  If unintentional this check on the sign of the variable can be removed and a few lines saved.  

Function in question: https://github.com/PandoraPFA/LArContent/blob/172e2a29683d1538989d075a1c78c9180b1d82f4/larpandoracontent/LArObjects/LArSupportVectorMachine.h#L297

**Comment by PandoraPFA** [comment]
Removed first of the two equivalent function returns.

Thanks!
